Fix Apicurito deploy match labels
Apicurio/apicurio-operators pull request #58
Opened 2021-04-22 21:30 UTC by claudio4j

Matchlabels should not be changed, as they are immutables.

2021-04-22 21:31 UTC, claudio4j commented
@lgarciaaco can you review and merge this fix ?

2021-04-22 21:38 UTC, phantomjinx requested changes
Is this also an issue with the deploy/deployment.yaml as well?

2021-04-22 21:39 UTC, phantomjinx commented
> @lgarciaaco can you review and merge this fix ?

I can review & merge, if Luis is not available.

2021-04-22 21:59 UTC, claudio4j commented
> Is this also an issue with the deploy/deployment.yaml as well?

there is no deploy/deployment.yaml, at least not in master branch.

2021-04-22 22:00 UTC, claudio4j commented
> I can review & merge, if Luis is not available.

Suggestion accepted :+1:

2021-04-23 04:57 UTC, phantomjinx commented
> > Is this also an issue with the deploy/deployment.yaml as well?
> 
> there is no deploy/deployment.yaml, at least not in master branch.

Sorry, its  https://github.com/Apicurio/apicurio-operators/blob/master/apicurito/deploy/operator.yaml

2021-04-23 12:35 UTC, claudio4j commented
> Sorry, its https://github.com/Apicurio/apicurio-operators/blob/master/apicurito/deploy/operator.yaml

This issue doesn't affect deploy/operator.yaml or the tools/components/components.go (that generates the operator.yaml).
Thanks for reviewing.

2021-04-23 12:54 UTC, phantomjinx commented
> > Sorry, its https://github.com/Apicurio/apicurio-operators/blob/master/apicurito/deploy/operator.yaml
> 
> This issue doesn't affect deploy/operator.yaml or the tools/components/components.go (that generates the operator.yaml).
> Thanks for reviewing.

Ah ... looks like the metering label in the operand is not updating rather than the operator. My mistake!

2021-04-23 12:54 UTC, phantomjinx approved these changes

2021-04-23 13:13 UTC, merged